version: "3.3"
services:
  postgres:
    container_name: pg15-master
    image: postgres:15.2
#     command:
#          ускорение вставки
#          - "-c"
#          - "fsync=off"
#          - "-c"
#          - "synchronous_commit=off"
#          - "-c"
#          - "full_page_writes=off"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: "socnetDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ${PWD}/dockers/pgmaster:/var/lib/postgresql/data/pgdata:rw
      - ${PWD}/dockers/pgmaster:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      socnet_network:
        ipv4_address: 172.21.0.11

  postgres-slave1:
    container_name: pg15-slave1
    image: postgres:15.2
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: "socnetDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ${PWD}/dockers/pgslave1:/var/lib/postgresql/data/pgdata:rw
      - ${PWD}/dockers/pgslave1:/docker-entrypoint-initdb.d
    ports:
      - "15432:5432"
    networks:
      socnet_network:
        ipv4_address: 172.21.0.21

#   postgres-slave2:
#     container_name: pg15-slave2
#     image: postgres:15.2
#     environment:
#       PGDATA: "/var/lib/postgresql/data/pgdata"
#       POSTGRES_DB: "socnetDB"
#       POSTGRES_USER: "postgres"
#       POSTGRES_PASSWORD: "postgres"
#     volumes:
#       - ${PWD}/dockers/pgslave2:/var/lib/postgresql/data/pgdata:rw
#       - ${PWD}/dockers/pgslave2:/docker-entrypoint-initdb.d
#     ports:
#       - "25432:5432"
#     networks:
#       socnet_network:
#         ipv4_address: 172.21.0.22

networks:
  socnet_network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.21.0.0/24