version: "3.3"
services:
  postgres:
    container_name: pg15
    image: postgres:15.2
    command:
          - "postgres"
          - "-c"
          - "max_connections=50"
          - "-c"
          - "shared_buffers=1GB"
          - "-c"
          - "effective_cache_size=4GB"
          - "-c"
          - "work_mem=16MB"
          - "-c"
          - "maintenance_work_mem=512MB"
          - "-c"
          - "random_page_cost=1.1"
          - "-c"
          - "temp_file_limit=10GB"
          - "-c"
          - "log_min_duration_statement=200ms"
          - "-c"
          - "idle_in_transaction_session_timeout=10s"
          - "-c"
          - "lock_timeout=1s"
          - "-c"
          - "statement_timeout=60s"
          - "-c"
          - "shared_preload_libraries=pg_stat_statements"
          - "-c"
          - "pg_stat_statements.max=10000"
          - "-c"
          - "pg_stat_statements.track=all"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: "socnetDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - ${PWD}/dockers/pgdata:/pgdata:rw
#        - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "5432:5432"
    networks:
      socnet_network:
        ipv4_address: 172.21.0.11

networks:
  socnet_network:
#    external: true
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.21.0.0/24