// Code generated by protoc-gen-go. DO NOT EDIT.
// source: soc-net.proto

package socnet

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRegisterRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	SecondName           string   `protobuf:"bytes,2,opt,name=SecondName,proto3" json:"SecondName,omitempty"`
	DateBirth            int64    `protobuf:"varint,3,opt,name=dateBirth,proto3" json:"dateBirth,omitempty"`
	Biography            string   `protobuf:"bytes,4,opt,name=biography,proto3" json:"biography,omitempty"`
	City                 string   `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterRequest) Reset()         { *m = UserRegisterRequest{} }
func (m *UserRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*UserRegisterRequest) ProtoMessage()    {}
func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4e10677feb35f37, []int{0}
}

func (m *UserRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterRequest.Unmarshal(m, b)
}
func (m *UserRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterRequest.Marshal(b, m, deterministic)
}
func (m *UserRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterRequest.Merge(m, src)
}
func (m *UserRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_UserRegisterRequest.Size(m)
}
func (m *UserRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterRequest proto.InternalMessageInfo

func (m *UserRegisterRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserRegisterRequest) GetSecondName() string {
	if m != nil {
		return m.SecondName
	}
	return ""
}

func (m *UserRegisterRequest) GetDateBirth() int64 {
	if m != nil {
		return m.DateBirth
	}
	return 0
}

func (m *UserRegisterRequest) GetBiography() string {
	if m != nil {
		return m.Biography
	}
	return ""
}

func (m *UserRegisterRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *UserRegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserRegisterResponse struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterResponse) Reset()         { *m = UserRegisterResponse{} }
func (m *UserRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*UserRegisterResponse) ProtoMessage()    {}
func (*UserRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4e10677feb35f37, []int{1}
}

func (m *UserRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterResponse.Unmarshal(m, b)
}
func (m *UserRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterResponse.Marshal(b, m, deterministic)
}
func (m *UserRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterResponse.Merge(m, src)
}
func (m *UserRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_UserRegisterResponse.Size(m)
}
func (m *UserRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterResponse proto.InternalMessageInfo

func (m *UserRegisterResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetUserRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4e10677feb35f37, []int{2}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetUserResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4e10677feb35f37, []int{3}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type LoginRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4e10677feb35f37, []int{4}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4e10677feb35f37, []int{5}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*UserRegisterRequest)(nil), "socnet.UserRegisterRequest")
	proto.RegisterType((*UserRegisterResponse)(nil), "socnet.UserRegisterResponse")
	proto.RegisterType((*GetUserRequest)(nil), "socnet.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "socnet.GetUserResponse")
	proto.RegisterType((*LoginRequest)(nil), "socnet.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "socnet.LoginResponse")
}

func init() { proto.RegisterFile("soc-net.proto", fileDescriptor_b4e10677feb35f37) }

var fileDescriptor_b4e10677feb35f37 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0xae, 0xd2, 0x40,
	0x14, 0xc6, 0xd3, 0x02, 0x55, 0x8e, 0x80, 0x3a, 0x20, 0xd6, 0x4a, 0x0c, 0xe9, 0x46, 0x24, 0xb1,
	0x4d, 0x74, 0xc7, 0x92, 0x18, 0x89, 0x89, 0x61, 0x51, 0xe2, 0x03, 0x0c, 0xed, 0xa4, 0x4c, 0x82,
	0x33, 0x75, 0xe6, 0x10, 0x43, 0x8c, 0x1b, 0xb7, 0x2e, 0x7d, 0x20, 0x1f, 0xe2, 0xbe, 0xc2, 0x7d,
	0x90, 0x9b, 0x4e, 0x87, 0xbf, 0x97, 0x7b, 0xef, 0xaa, 0x3d, 0xdf, 0x77, 0xce, 0x6f, 0xfa, 0x9d,
	0x29, 0xb4, 0xb5, 0x4c, 0xdf, 0x0b, 0x86, 0x51, 0xa1, 0x24, 0x4a, 0xe2, 0x69, 0x99, 0x0a, 0x86,
	0xc1, 0x20, 0x97, 0x32, 0x5f, 0xb3, 0x98, 0x16, 0x3c, 0xa6, 0x42, 0x48, 0xa4, 0xc8, 0xa5, 0xd0,
	0x55, 0x57, 0xf8, 0xdf, 0x81, 0xee, 0x37, 0xcd, 0x54, 0xc2, 0x72, 0xae, 0xb1, 0x7c, 0xfe, 0xd8,
	0x30, 0x8d, 0x64, 0x00, 0xcd, 0xcf, 0x5c, 0x69, 0x9c, 0xd3, 0xef, 0xcc, 0x77, 0x86, 0xce, 0xa8,
	0x99, 0x1c, 0x04, 0xf2, 0x06, 0x60, 0xc1, 0x52, 0x29, 0x32, 0x63, 0xbb, 0xc6, 0x3e, 0x52, 0xca,
	0xe9, 0x8c, 0x22, 0x9b, 0x72, 0x85, 0x2b, 0xbf, 0x36, 0x74, 0x46, 0xb5, 0xe4, 0x20, 0x94, 0xee,
	0x92, 0xcb, 0x5c, 0xd1, 0x62, 0xb5, 0xf5, 0xeb, 0x15, 0x7b, 0x2f, 0x10, 0x02, 0xf5, 0x94, 0xe3,
	0xd6, 0x6f, 0x18, 0xc3, 0xbc, 0x93, 0x00, 0x1e, 0x17, 0x54, 0xeb, 0x9f, 0x52, 0x65, 0xbe, 0x67,
	0xf4, 0x7d, 0x1d, 0x46, 0xd0, 0x3b, 0x0d, 0xa0, 0x0b, 0x29, 0x34, 0x23, 0x7d, 0xf0, 0x4a, 0xfd,
	0xcb, 0x27, 0xfb, 0xf9, 0xb6, 0x0a, 0x47, 0xd0, 0x99, 0x31, 0xac, 0x46, 0xaa, 0xac, 0x77, 0x75,
	0xbe, 0x83, 0xa7, 0xfb, 0xce, 0x03, 0x74, 0x81, 0x14, 0x37, 0x7a, 0xd7, 0x5a, 0x55, 0xe1, 0x14,
	0x5a, 0x5f, 0x65, 0xce, 0xc5, 0x03, 0xc8, 0x93, 0x20, 0xee, 0x59, 0x90, 0xb7, 0xd0, 0xb6, 0x8c,
	0xfb, 0x0f, 0xfb, 0xf0, 0xd7, 0x05, 0x6f, 0x21, 0xd3, 0x39, 0x43, 0x92, 0x41, 0xeb, 0x38, 0x3c,
	0x79, 0x1d, 0x55, 0xb7, 0x1e, 0x5d, 0xb8, 0xd3, 0x60, 0x70, 0xd9, 0xac, 0x4e, 0x0b, 0x5f, 0xfd,
	0xb9, 0xba, 0xfe, 0xe7, 0x76, 0xc3, 0x4e, 0xbc, 0xd1, 0x4c, 0xc5, 0xca, 0xfa, 0x13, 0x67, 0x4c,
	0x12, 0x78, 0x64, 0x17, 0x41, 0xfa, 0x3b, 0xc6, 0xe9, 0x0e, 0x83, 0x97, 0xb7, 0x74, 0x8b, 0xed,
	0x1b, 0xec, 0x33, 0x62, 0xb1, 0x39, 0xc3, 0xf8, 0x17, 0xcf, 0x7e, 0x93, 0x19, 0x34, 0x4c, 0x5a,
	0xd2, 0xdb, 0x4d, 0x1e, 0x2f, 0x30, 0x78, 0x71, 0xa6, 0x5a, 0xda, 0x73, 0x43, 0x7b, 0x12, 0x7a,
	0xf1, 0xba, 0xd4, 0x27, 0xce, 0x78, 0xe9, 0x99, 0x1f, 0xf9, 0xe3, 0x4d, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x81, 0x4b, 0x42, 0x30, 0xff, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SocNetClient is the client API for SocNet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SocNetClient interface {
	UserRegister(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*UserRegisterResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type socNetClient struct {
	cc *grpc.ClientConn
}

func NewSocNetClient(cc *grpc.ClientConn) SocNetClient {
	return &socNetClient{cc}
}

func (c *socNetClient) UserRegister(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*UserRegisterResponse, error) {
	out := new(UserRegisterResponse)
	err := c.cc.Invoke(ctx, "/socnet.SocNet/UserRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socNetClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/socnet.SocNet/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socNetClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/socnet.SocNet/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocNetServer is the server API for SocNet service.
type SocNetServer interface {
	UserRegister(context.Context, *UserRegisterRequest) (*UserRegisterResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

// UnimplementedSocNetServer can be embedded to have forward compatible implementations.
type UnimplementedSocNetServer struct {
}

func (*UnimplementedSocNetServer) UserRegister(ctx context.Context, req *UserRegisterRequest) (*UserRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRegister not implemented")
}
func (*UnimplementedSocNetServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedSocNetServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterSocNetServer(s *grpc.Server, srv SocNetServer) {
	s.RegisterService(&_SocNet_serviceDesc, srv)
}

func _SocNet_UserRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocNetServer).UserRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socnet.SocNet/UserRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocNetServer).UserRegister(ctx, req.(*UserRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocNet_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocNetServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socnet.SocNet/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocNetServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocNet_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocNetServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socnet.SocNet/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocNetServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SocNet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "socnet.SocNet",
	HandlerType: (*SocNetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserRegister",
			Handler:    _SocNet_UserRegister_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _SocNet_GetUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _SocNet_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "soc-net.proto",
}
